name: QA Build
on:
  push:
    branches: [ github-actions-test ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
      
    - name: Configure git
      run: bash scripts/configure-git-for-actions.sh

    - name: build
      run: npm install && npm update && npm run github-build
    
    - name: dist
      run: npm run dist
    
    - name: commit
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit build plist files"
        add: "src/safari-app-extension/AlpheiosSafari/Info.plist src/safari-app-extension/AlpheiosReadingTools/Info.plist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
