name: QA Build
on:
  push:
    branches: [ github-actions-test ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
      
    - name: build
      id: run_build
      run: npm install && npm update && npm run github-build
    
    - name: update env
      run: bash scripts/update_env.sh ${{secrets.AUTH0_CLIENT_ID}}
      
    - name: dist
      run: npm run dist
    
    - name: commit
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit files for build ${steps.run_build.outputs.buildName}"
        add: "src/safari-app-extension/AlpheiosSafari/Info.plist src/safari-app-extension/AlpheiosReadingTools/Info.plist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.run_build.outputs.buildName }}
        release_name: Release ${{ steps.run_build.outputs.buildName }}
        draft: false
        prerelease: true
    
    - name: Upload dist
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist.zip
        asset_name: dist.zip
        asset_content_type: application/zip
